### ISSUE TITLE
Init.txt Format Error!

### ISSUE THREAD

**Issue by erik-wien** [MakeMagazinDE/LED-Laufschrift#1]
Mit nur minimaler Anpassung der init.TXT wird ein Formatierungsfehler für Zeile 22 ausgegeben. Dort ist kein CR/LF. Nachdem ich die Prüfroutine dort rausgenommen habe, kann sich der ESP weder mit meinem WLAN verbinden, noch macht er einen Hotspot.

Entweder ich hab was bei der Installationsanweisungen übersehen, oder dieses Projekt geht gar nicht. 

Any hints?

**Comment by ledidier** [comment]
Bei mir das Gleiche: Autostart mode format error bei der seriellen Ausgabe nachdem Init.txt geöffnet wurde. Der Fehler obwohl ich die Datei unter Linux bearbeitet habe und auch nach der Zeile 22 sich kein CR/LF befindet.
Im 2.ten Versuch habe ich die Originaldatei (ohne Modifikation) genutz - gleicher Fehler.

Bin ratlos!

**Comment by Ptschulik** [comment]
Hallo,
melde mich als Entwickler und Veröffentlicher des Make Artikels. 
Das Verhalten ist mir ein wenig schleierhaft. Habe mir gerade die Init.txt heruntergeladen und nochmals über Tools --> ESP32 Sketch Data Upload auf den ESP32 geladen. Alles funktioniert wie beschrieben und ein Access Point wird aufgebaut.
Habe mir auch nochmals en kompletten Code von der Make Seite downloaded und neu kopiliert auf aufgespielt. Funktioniert ebenfalls!
Verwendet ihr ein ESP32 Pico Kit? Ist in den Einstellungen das Partition Scheme auf "Default" gestellt?
Wurde der ESP32 schon mal mit einer älteren Version von des ESP board managers programmiert? Ich verwende derzeit die Version 1.0.4 des Board Managers.

Schaut in Notepad die Datei nach dem Einschalten von "Alle zeichen anzeigen" wirklich so aus?
![grafik](https://user-images.githubusercontent.com/88718968/128864828-52ff2e7d-821b-428c-b7d3-d37cd2bb7d63.png)

Ihr könnt auch gerne hier Euer Init.txt posten, dann probiere ich es bei mir aus
Peter

**Comment by erik-wien** [comment]
Hi Ptschulik,

Kann jetzt noch nicht alle Fragen beantworten, weil ich noch im Büro bin.  

Ist ein esp32 wroom Entwicklerboard auf dem schon ein temperaturfühler mit html Server und Wled gelaufen sind.  

Mir ist nur aufgefallen, dass im Code beim checken der letzten Zeile der init.txt eine IP Adressen Variable getestet zu werden scheint, was mich misstrauisch gemacht hat.  

Liebe Grüsse   Erik

**Comment by Ptschulik** [comment]
Die letzte Zeile die gecheckt wird der Autostart Eintrag und keine IP-Adresse. Der Code dazu befindet sich unter "Basis.ino" in den Zeilen 1321-1353. Eigentlich sollten Sie ja mit Debug On genau sehen, bis wohin das Init-File abgearbeitet wird. Beim letzten Parametre wird nur gecheck, ob er 1 oder 2 ist. Vielleicht posten Sie auch hier die Debug Infos, dann kann ich vielleicht schnell sehen, woran es liegt!

**Comment by ledidier** [comment]
Hallo Ptschulik,

Ich verwende einen ESP32 Wroom (AZ-Delivery). Die Arduino IDE läuft bei mir auf Linux.
Hier ist der Debug-Inhalt des seriellen Terminals:

20:08:42.438 -> *********************************************************
20:08:42.438 -> * LED text scrolling display with ESP32                 *
20:08:42.438 -> *                                                       *
20:08:42.438 -> * V2.0                                      @PT 2020    *
20:08:42.438 -> *********************************************************
20:08:42.438 -> 
20:08:42.438 -> 
20:08:42.438 -> 
20:08:42.438 -> 
20:08:42.438 -> 
20:08:42.438 -> Debug is enabled...
20:08:42.438 -> 
20:08:42.438 -> Initialisation of FLASH memory ...
20:08:42.438 -> Memory location 0: Remote update flag: 0 (Normal boot = 0, Remote update = 1)
20:08:42.471 -> 
20:08:42.471 -> Step 1: Initialise LED-Display: Done
20:08:42.471 -> 
20:08:42.471 -> Step 2: Initialise file access and read Init.txt...
20:08:42.471 ->   Initialize file access: Done
20:08:42.570 ->   Open file Init.txt: Done
20:08:42.637 ->   Read Init.txt content: 
20:08:42.637 ->     Autostart mode to display text message after boot set to: Autostart mode format error!

Natürlich liegt es nahe die Formatierung der Init.txt als Ursache des Übels in den Blick zu nehmen. Die üblichen Editoren unter Linux haben auch jeweils ein LR/CF in der letzten Zeile (22) automatisch eingefügt. 

![Bildschirmfoto zu 2021-08-10 20-17-56](https://user-images.githubusercontent.com/56477093/128913832-9ec781b7-f430-4407-a997-408e77ef69e2.png)


Nachdem ich aber die Endsequenz entfernt habe, hat sich das Problem leider nicht erledigt. Leider habe ich immer noch die gleiche Fehlermeldung.


Ich werde weiter mein Glück versuchen.

**Comment by ledidier** [comment]
Hallo Ptschulik,

ich hab nun mit Notepad++ mein Glück versucht - leider auch erfolglos!




![Bildschirmfoto zu 2021-08-10 20-30-25](https://user-images.githubusercontent.com/56477093/128915324-2dd4c836-d0cb-4355-88d6-8fc4b34746e3.png)

**Comment by Ptschulik** [comment]
Hi,
das klingt nach einem ganz verrückten Problem.
Nach den Debug Meldungen kann ich wie folgt zusammenfassen:
1. Das Init.txt wird korrekt geöffnet und es hat die korrekte Anzahl an Zeilen, d.h. es liegt auch korrekt im Speicher des ESP32
2. Bis zur Zeile 21 wird alles korrekt eingelesen und verarbeitet
3. Irgendwas geht schief beim Einlesen des einen Zeichens in der Zeile 22 (im Code Zeile 1302 - 1307)
4. Bei der Überprüfung des Wertes (im Code Zeile 1327 und 1328) muss etwas schiefgeben, dass die Fehlermeldung veranlasst!

Ich habe keinerlei LInux-Erfahrung, aber es kann wohl nur damit zusammenhängen, wie Linux das File abschließt.
Könnten Sie mir bitte Ihr Init.txt File an meine E-Mail Adresse peter.tschulik@chello.at zusenden, damit ich weitere Tests bzw. Analysen machen kann.
Wäre doch gelacht, wenn wir das Ding nicht zum Laufen bringen!
Peter TSCHULIK

**Comment by ledidier** [comment]
Hallo Peter,

ich habe mal testhalber das Betriebssystem gewechselt auf WIN10.
Gleiches Problem, also liegt es wohl am ESP32 ([Link zum Board](https://www.az-delivery.de/products/esp32-developmentboard)). Als Board habe ich in der IDE das Modell "ESP32 Dev Module" ausgewählt. 
Ich werde das Board einmal total "erasen" und dann komplettt neu beschreiben. Bis jetzt hatte ich noch nie Probleme mit dem NodeMCU.
So schnell geb´ ich nicht auf!  :-)

P.S. mit dem File hat´s sich ja wohl erübrigt?!

Jochen

**Comment by Ptschulik** [comment]
Hallo Jochen,
danke für die Info. 
Ich sollte irgendwo in der Lade ein ähnliches Board haben. Werde es mal mit diesem probieren.
Ich kann mir einfach nicht vorstellen, dass es an einem ESP board liegt.
Was mich wirklich interessieren würde und was ich mit deinem Init-File probieren wollte ist, welcher Wert die Zeile 22 das Init.txt ausliest.
Du könntest das mal probieren indem du nach der Zeile 1225 hinzufügst (vor dem #endif)
Serial.print ("*");
Serial.print (IP_ADDRESS_STRING);
Serial.println ("*");
und nach der Zeile 1349
Serial.println (TEST_INT);
 
Dann wüssten wir 
a. Ob mehr als ein Zeichen eingelesen wird
b. Ob die Umwandlung in eine Zahl funktioniert

Peter

**Comment by ledidier** [comment]
Hallo Peter,

hier der Debug:

Debug is enabled...

Initialisation of FLASH memory ...
Memory location 0: Remote update flag: 0 (Normal boot = 0, Remote update = 1)

Step 1: Initialise LED-Display: Done

Step 2: Initialise file access and read Init.txt...
  Initialize file access: Done
  Open file Init.txt: Done
  Read Init.txt content: 
    Autostart mode to display text message after boot set to: 0
Autostart mode format error!

Jochen

**Comment by ledidier** [comment]
Hallo Peter,

ich habe, nachdem mir es komisch vorkam, dass 

 Serial.print ("");
 Serial.print (IP_ADDRESS_STRING);
 Serial.println ("");_

Nichts anzeigt, den Code-Snipsel vor " Serial.print ("    Autostart mode to display text message after boot set to: ");"  (bei mir Zeile 1328) gesetzt.
Aber auch dort wird der String IP_ADDRESS_STRING nicht angezeigt sondern nur die beiden Leerzeichen, bzw. den Zeilenumbruch. Der Inhalt vom String fehlt.

Jochen

**Comment by Ptschulik** [comment]
Hallo Jochen,
schick mir bitte doch einmal das Init.txt file per mail an meine Email-Adresse. Mal sehen was ich finde!
Peter

**Comment by ledidier** [comment]
Ok - bin aber aktuell unterwegs. 
Dauert ein Wenig.

Am 11. August 2021 15:33:30 MESZ schrieb Ptschulik ***@***.***>:
>Hallo Jochen,
>schick mir bitte doch einmal das Init.txt file per mail an meine Email-Adresse. Mal sehen was ich finde!
>Peter
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MakeMagazinDE/LED-Laufschrift/issues/1#issuecomment-896831475
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Ptschulik** [comment]
Hi,
ich habe jetzt zwei Dinge probiert!
1. Habe ein ESP32 Dev. Board genommen und konnte alles ohne Fehler installieren. Init.txt konnte ohne Probleme geladen werden
2. Habe dein Init.txt File genommen und eingespielt. Auch hier kein Fehler

Ich bin wirklich verzweifelt. Es kann dann weder am Board noch an deinem Init.txt File liegen!
Welche Arduino IDE Version verwendest du? Welche Version für den ESP32 Board Manager?
Peter

**Comment by ledidier** [comment]
Hallo Peter,

aktuell verwende ich die 1.8.13 Version von der Arduino IDE. Der Board-Manager (https://dl.espressif.com/dl/package_esp32_index.json) von Espressif Systems hat die Version 1.0.6.
Hast Du deinen Test mit dem AZ Delivery ESP32-WROOM-32 durchgeführt, oder was anderes?

Ich habe, wie gesagt, an verschiedenen Systemen (Linux, WIN) mit diesem Teil immer das gleiche Ergebnis. Meiner Meinung nach ist das Board daran Schuld. Ich habe leider nur noch einen ESP32-DOWDQ6 gehabt, der auch das gleiche fehlerhafte Ergebnis liefert :-(

ich bleib dran!

Jochen

**Comment by Ptschulik** [comment]
Hi,
den Test habe ich mit einer NodeMCU gemacht (siehe Bild). Habe leider keinen AZ Delivery ESP32!
![20210812_211720](https://user-images.githubusercontent.com/88718968/129256383-60ceda72-ef34-4bf5-b4cf-bdfa43de9623.jpg)
![20210812_211725](https://user-images.githubusercontent.com/88718968/129256390-c10fe57c-8f7c-4d92-b145-d57d36e25f0f.jpg)

**Comment by Ptschulik** [comment]
Eine Sache, die mich nun stutzig macht. Bei mir schaut der Debug Inhalt ziemlich verschieden aus:
Debug is enabled...

Memory location 0: Remote update flag: 0 (Normal boot = 0, Remote update = 1)

Step 1: Initialise LED-Display: Done

Step 2: Initialise file access and read Init.txt...
  Initialize file access: Done
  Open file Init.txt: Done
  Read Init.txt content: 
    AP WLAN SSID: LED_Text
    AP WLAN password: default_pw
    AP fixed IP-Address: 192.168.122.2
    AP subnet mask: 255.255.255.0
    STA WLAN SSID: LED_IOT
    STA WLAN password: default_pw
    STA hostname: Laufschrift
    STA fixed IP-Address: 192.168.123.234
    STA subnet mask: 255.255.255.0
    STA gateway IP-Address: 192.168.123.1
    STA DNS 1 IP-Address: 195.58.161.123
    STA DNS 2 IP-Address: 212.186.211.21
    Boot mode set to: Accesss Point (AP)
    Text message: Make: Das Magazin
    Text scrolling set to: Static text
    Message brightness set to: 10 (2 = Lowest, 7, 10, 13, 15 = Brightest)
    Message speed set to: 30 (10 = Fastest, 20, 30, 40, 50 = Slowest)
    Font set to: Font 1: Own font
    Char spacing set to: 1 pixels
    Text type set to: Text message, text set to: Make: Das Magazin
    Inverting effect set to: Off
    Autostart mode to display text message after boot set to: On

D.h, bei dir werden das File schon vorher nicht richtig gelesen! Sonst würden bis dahin die Meldungen korekt angezeigt. So als ob der LINE_COUNTER oder der LOOP_COUNTER nicht richtig funktionieren. Ich werde morgen mal versuchen die Version 1.0.6 bei mir zu laden, ob sich da etwas grundsätzliches beim Lesen von Files geändert hat!

**Comment by Ptschulik** [comment]
Also an der ESP Board Version liegt es auch nicht! Funktiniert bei mir mit 1.0.6 genauso!

**Comment by ledidier** [comment]
Hallo Peter,

Ich würde dir gerne den AzDelivery ESP32 zum Testen schicken! Ich hab 5 Stück davon. Also kein Problem. Ich kann auf den verzichten.
Hast Du eine Adresse über deinen Verlag?

Grüße
Jochen

Am 12. August 2021 21:40:21 MESZ schrieb Ptschulik ***@***.***>:
>Also an der ESP Board Version liegt es auch nicht! Funktiniert bei mir mit 1.0.6 genauso!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MakeMagazinDE/LED-Laufschrift/issues/1#issuecomment-897916616
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Ptschulik** [comment]
Meine Adresse lautet:
Peter Tschulik
Zentagasse 40-42/3/8
1050 Wien

**Comment by erik-wien** [comment]
Es ist einfacher, wenn ich Peter meinen bring. Hab auch zwei und lebe auch in wien.

**Comment by Ptschulik** [comment]
Das ist eine gute Idee! Ich bin nur ab morgen auf Urlaub bis nächsten Sonntag. Melde mich dann!

**Comment by erik-wien** [comment]
Hi Ptschulik,

Sehr gerne!

**Comment by Ptschulik** [comment]
Hallo Erik,
bin ab Sonntag Nachmittag wieder in Wein. Kannst Du mich mal unter 0664 4202358 anrufen, wo und wann ich mir den ESP32 abholen könnte?
Peter

**Comment by erik-wien** [comment]
Hi Ptschulik,

Im Moment sind wir in der Steiermark. Ansonsten kein Problem. Wir wohnen nur drei 59er Stationen auseinander. ;)

**Comment by Ptschulik** [comment]
Ah Ok. Bitte gib einfach Bescheid, wenn wieder in Wien
Peter

**Comment by Ptschulik** [comment]
Guten morgen,
habe gestern von Erik zwei AZ-Delivery ESP32 Dev Kits erhalten!
Zuerst war ich ganz glücklich, da ich auf dem ersten Board den Fehler exakt wie von Euch beschrieben nachstellen konnte.
D.h. ich habe zuerst mit ESP Sketch Data Upload die Daten aufgespielt und dann das Programm kompiliert/aufgespielt.
Danach war der Fehler wie von Euch beschrieben reproduzierbar. Nachdem ich danach nochmals mit ESP Sketch Data Upload die Daten aufgespielt habe, hat alles funktioniert und das Einlesen der Init.txt Daten hat funktioniert.
Beim zweiten Board hat alles gleich von Anfang an funktioniert!

Ich bin wieder mit meinem Latein am Ende:
Es kann dann nur ein Timingproblem beim Upload oder eine Inkompatibilität des Boards sein
Hier nochmals meine Einstellungen:
ESP Sketch Data Upload: Meine Datei "esp32fs.jar" unter Tools ist vom 15.01.2019. Keine Ahnung wie bzw. ob man eine Version herausfinden kann.
Beim Daten upload wird folgendes angezeigt:
[SPIFFS] data   : D:\Privat\Arduino\Programme\LED_Laufschrift_Make\data
[SPIFFS] start  : 2686976
[SPIFFS] size   : 1472
[SPIFFS] page   : 256
[SPIFFS] block  : 4096
/Bootloader.html

/Init.txt

/Main.html

/Reboot.html

/Style.css

/Submenu1.html

/Submenu2.html

/Submenu3.html

/Submenu4.html

/Submenu5.html

/Submenu6.html

[SPIFFS] upload : C:\Users\petert\AppData\Local\Temp\arduino_build_350859/LED_Laufschrift_Make.spiffs.bin
[SPIFFS] address: 2686976
[SPIFFS] port   : COM6
[SPIFFS] speed  : 921600
[SPIFFS] mode   : dio
[SPIFFS] freq   : 80m

esptool.py v3.0-dev

Serial port COM6

Connecting........_____.....__

Chip is ESP32-D0WDQ6 (revision 1)

Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None

Crystal is 40MHz

MAC: 24:62:ab:f4:81:7c

Uploading stub...

Running stub...

Stub running...

Changing baud rate to 921600

Changed.

Configuring flash size...

Auto-detected Flash size: 4MB

Compressed 1507328 bytes to 11822...

Writing at 0x00290000... (100 %)

Wrote 1507328 bytes (11822 compressed) at 0x00290000 in 0.2 seconds (effective 77298.8 kbit/s)...

Hash of data verified.



Leaving...

Hard resetting via RTS pin...

Vielleicht gibt es ja hier Abweichungen?

Folgende Einstellungen habe ich in der Arduino IDE:
Board "ESP Dev Module"
Upload speed "921600"
CPU Frequency "240Mhz (Wifi/BT)"
Flash Frequency: "80 MHz"
Flash Mode "QIO"
Flash Size: "4MB (32MB"
Partion Scheme "Default 4MB with spliffs (1.2MB APP/1.5MB SPLIFFS)"
Core Debug Level: "None"
PSRAM: "Disabled"

Bitte checked das mit Euren Einstellungen
Peter

**Comment by erik-wien** [comment]
Hi Ptschulik,

Hm. Das ist ärgerlich. Klingt als ob Du bist bs über die Schulter schauen musst um herauszufinden an welcher Stelle wir was falsch machen …

**Comment by ledidier** [comment]
Hi Ptschulik,

ich hab' nochmal meine Einstellungen bzgl. des Boards überprüft. 
Bei mir sind die zu 100% identisch:

_Der Sketch verwendet 906726 Bytes (69%) des Programmspeicherplatzes. Das Maximum sind 1310720 Bytes.
Globale Variablen verwenden 43672 Bytes (13%) des dynamischen Speichers, 284008 Bytes für lokale Variablen verbleiben. Das Maximum sind 327680 Bytes.
esptool.py v3.0-dev
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: b8:f0:09:ca:f5:08
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 32074.4 kbit/s)...
Hash of data verified.
Compressed 18656 bytes to 12053...
Writing at 0x00001000... (100 %)
Wrote 18656 bytes (12053 compressed) at 0x00001000 in 0.1 seconds (effective 1044.9 kbit/s)...
Hash of data verified.
Compressed 906848 bytes to 520758...
Writing at 0x00010000... (3 %)
...
Writing at 0x0008c000... (100 %)
Wrote 906848 bytes (520758 compressed) at 0x00010000 in 8.3 seconds (effective 872.2 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 8062.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin..._



Ich habe, auf den Verdacht, dass das es hin und wieder funktioniert, mehrer Versuche unternommen. Vielleicht habe ich ja Glück. Leider Nein.

Grüße

Jochen

**Comment by Ptschulik** [comment]
Hi,
es war eh eher unwahrscheinlich, dass es an den Boardeinstellunen liegt und damit beim Uplad des Programs.
Ich glaube dass es eher an den ESP Sketch Data Upload liegt, d.h, dass die hochgeladenen Files irgendwie korumpiert werden.
Kannst Du mir mal den Log zum ESP Sketch Data Upload schicken wie in meinem Post und das Datum der Datei "esp32fs.jar"?
Peter

**Comment by erik-wien** [comment]
Mein Protokoll lautet:

````
22:08:56.478 -> *********************************************************
22:08:56.478 -> * LED text scrolling display with ESP32                 *
22:08:56.511 -> *                                                       *
22:08:56.511 -> * V2.0                                      @PT 2020    *
22:08:56.511 -> *********************************************************
22:08:56.511 -> 
22:08:56.511 -> 
22:08:56.511 -> 
22:08:56.511 -> 
22:08:56.511 -> 
22:08:56.511 -> Debug is enabled...
22:08:56.511 -> 
22:08:56.511 -> Initialisation of FLASH memory ...
22:08:56.511 -> Memory location 0: Remote update flag: 0 (Normal boot = 0, Remote update = 1)
22:08:56.511 -> 
22:08:56.511 -> Step 1: Initialise LED-Display: Done
22:08:56.544 -> 
22:08:56.544 -> Step 2: Initialise file access and read Init.txt...
22:08:56.544 ->   Initialize file access: E (64) SPIFFS: mount failed, -10025
22:09:22.667 -> Done
22:09:22.667 ->   Open file Init.txt: Done
22:09:22.733 ->   Read Init.txt content: 
22:09:22.733 ->     Autostart mode to display text message after boot set to: On
22:09:22.733 -> 
22:09:22.733 -> 
22:09:22.733 -> 
22:09:22.733 -> 
22:09:22.733 -> >> Press enter to change Init.txt settings within 3 seconds ...
22:09:25.753 -> 
22:09:25.753 -> Step 3: Create WLAN Access point with SSID '' and password '': dhcps_start(): could not obtain pcb
22:09:25.952 -> Done
22:09:25.952 ->     Use this URL: http://0.0.0.0/main
22:09:27.967 -> 
22:09:27.967 -> Step 4: Define routes for answers from web page: Done
22:09:27.967 -> 
22:09:27.967 -> Initialisation finished! Ready to receive requests ...
22:09:27.967 -> 
````
bzw.

`````
Sketch uses 906370 bytes (69%) of program storage space. Maximum is 1310720 bytes.
Global variables use 43672 bytes (13%) of dynamic memory, leaving 284008 bytes for local variables. Maximum is 327680 bytes.
esptool.py v3.0-dev
Serial port /dev/cu.usbserial-0001
Connecting........_____....._____....._____....._____.
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 7c:9e:bd:37:26:1c
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 8224.7 kbit/s)...
Hash of data verified.
Compressed 18656 bytes to 12053...
Writing at 0x00001000... (100 %)
Wrote 18656 bytes (12053 compressed) at 0x00001000 in 1.1 seconds (effective 140.3 kbit/s)...
Hash of data verified.
Compressed 906480 bytes to 520506...
Writing at 0x00010000... (3 %)
…
Writing at 0x0007c000... (87 %)
Writing at 0x00080000... (90 %)
Writing at 0x00084000... (93 %)
Writing at 0x00088000... (96 %)
Writing at 0x0008c000... (100 %)
Wrote 906480 bytes (520506 compressed) at 0x00010000 in 46.0 seconds (effective 157.8 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 1541.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

`````
Wenn Du willst schick ich Dir mein init.txt oder den ganzen Code.

Liebe Grüsse   Erik

**Comment by Ptschulik** [comment]
Hallo Erik,
nach der Fehlermeldung her (in Step 2) kann der Flah Speicher nicht initialisiert werden, was eben auf ein Problem mit dem ESP Sketch Data Upload hindeutet! Auch du schickst mir nicht das Protokoll das ich bräuchte! Dass der Code richtig compiliert und aufgespielt wird ist NICHT das Problem. Es MUSS ein Problem beim Aufspielen der Webseiten und des Files INIT.TXT geben.
Daher bräuchte ich den Log der beim ESP Sketch Data Upload generiert wird! Bei mir schaut es so aus:

[SPIFFS] data : D:\Privat\Arduino\Programme\LED_Laufschrift_Make\data
[SPIFFS] start : 2686976
[SPIFFS] size : 1472
[SPIFFS] page : 256
[SPIFFS] block : 4096
/Bootloader.html

/Init.txt

/Main.html

/Reboot.html

/Style.css

/Submenu1.html

/Submenu2.html

/Submenu3.html

/Submenu4.html

/Submenu5.html

/Submenu6.html

[SPIFFS] upload : C:\Users\petert\AppData\Local\Temp\arduino_build_350859/LED_Laufschrift_Make.spiffs.bin
[SPIFFS] address: 2686976
[SPIFFS] port : COM6
[SPIFFS] speed : 921600
[SPIFFS] mode : dio
[SPIFFS] freq : 80m

esptool.py v3.0-dev

Serial port COM6

Connecting........___.....

Chip is ESP32-D0WDQ6 (revision 1)

Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None

Crystal is 40MHz

MAC: 24:62🆎f4:81:7c

Uploading stub...

Running stub...

Stub running...

Changing baud rate to 921600

Changed.

Configuring flash size...

Auto-detected Flash size: 4MB

Compressed 1507328 bytes to 11822...

Writing at 0x00290000... (100 %)

Wrote 1507328 bytes (11822 compressed) at 0x00290000 in 0.2 seconds (effective 77298.8 kbit/s)...

Hash of data verified.

Leaving...

Hard resetting via RTS pin...

**Comment by erik-wien** [comment]
Ok. Dann back to basics.

Welche Datei muss ich in Arduio laden? Ich habe `LED_Laufschrift_ESP32.ino` geladen und sehe die Tabs `LED_Laufschrift_ESP32`, `Basis`, `Led`, `Web` und `fontdata.h`.

Aus dem Tab `LED_Laufschrift_ESP32`starte ich den Upload und sehe dann das Protokoll wie oben im zweiten Teil gezeigt. Das schaut ähnlich aber nicht gleich aus wie bei Dir. Wo wird definiert, welche Dateien hochgeladen werden müssen?

**Comment by erik-wien** [comment]
Ok, mit Tools/Debug Level `Verbose` bekomme ich jetzt mehr Infos, aber immer noch keinen Dateiliste. Gibts da noch irgendwo ein Häkchen das man setzen kann?

**Comment by Ptschulik** [comment]
Vielleicht haben wir nun den Grund deines Problems gefunden. Im Artikel ist eigentlich beschrieben, dass es NICHT reicht nur das *.ino zu laden und zu kompilieren. Die Webseiten sowie die Init.txt müssen mit ESP Sketch Data upload vor oder nach dem Upload des Programs auf den ESP kopieren. Dazu musst du ein Add On installieren. Ein Tutorial findest du unter https://randomnerdtutorials.com/install-esp32-filesystem-uploader-arduino-ide/
Mir war nicht bewusst, das das aus dem Artikel nicht ersichtlich ist.
Mit dem eigenen Eintrag in der Arduino IDE werden dannn die Files aus dem Directory Data hochgeladen.
Wenn du willst kann ich auch noch Screenshots hochladen

**Comment by ledidier** [comment]
Hallo Peter!
DAS war der Fehler. Tut mir leid, aber bis dato hatte ich keine Anwendung am Arduino, ESP usw. bei der man Daten noch nachträglich hochladen muss. Sorry!

Trotz allem Vielen Vielen Dank für den Support!
Jetzt weiß ich wenigsten etwas mehr - man lernt nie aus!


LG
Jochen

**Comment by mobfactor** [comment]
Hallo, erstmal danke für das tolle Projekt,, ich finde es großartig!
Die Anleitung finde ich soweit verständlich, ich habe es zumindest im AP-Modus zum laufen bekommen. Der STA-Modus funktioniert bei mir nicht, da meine Fritzbox ein PW mit 20 Zeichen verwendet, das Programm aber nur 16 Stellen akzeptiert, wie kann man das ändern? Ich bin in C nicht so bewandert...
Es ist auf jeden Fall so, dass ein PW mit mehr als 16 Zeichen zu einem init fail beim ESP32 Sketch data upload führt, und zwar reproduzierbar. 

LG
Marcus

**Comment by erik-wien** [comment]
Yep. Das war’s.

**Comment by mobfactor** [comment]
?

**Comment by mobfactor** [comment]
@erik-wien 
Hast Du eine Lösung?

**Comment by Ptschulik** [comment]
Hi mobfactor,
die Variablen STA_WLAN_PWD im Hauptprogramm (Zeile 177) ist schon einmal für 20 Zeichen initialisiert. Du könntest sie zur Sicherheit weiter erhöhen, z.B.: char STA_WLAN_PWD [23] = {0};
Bei "Basis.ino" in Zeile 648 müsstest du ändern in "if ((LOOP_COUNTER > 1) && (LOOP_COUNTER < 21))" um 20 Zeichen zu erlauben
Wenn du das auch bei den manuellen Einstellungen ändern willst musst du auch Zeile 1790 in "if ((LOOP_COUNTER > 1) && (LOOP_COUNTER < 21))"  ändern
Probiere das mal
Peter

**Comment by erik-wien** [comment]
> @erik-wien
> Hast Du eine Lösung?

Ja, siehe zwei Absätze darüber:

> … Die Webseiten sowie die Init.txt müssen mit ESP Sketch Data upload vor oder nach dem Upload des Programs auf den ESP kopieren. Dazu musst du ein Add On installieren.  …

**Comment by mobfactor** [comment]
@Ptschulik 
es funktioniert jetzt! Vielleicht solltest Du das im Code ändern? Ich vermute, viele Nutzer in Deutschland haben eine Fritzbox und nehmen das 20 stellige Standardpasswort. Auf das Problem muss man als Hobbycoder ja erstmal kommen...
Danke für die prompte Kommunikation!

LG

Marcus

**Comment by Ptschulik** [comment]
Kann ich gerne mit einem Update machen. Ich warte mal ob es weitere Problem gibt

**Comment by oRKapro** [comment]
@Ptschulik
Vielleicht könnte die **README.md** hierzu angepasst und die entsprechenden Informationen eingefügt werden um selbst diese Änderungen vorzunehmen.
