### ISSUE TITLE
Passwort kann nicht länger als 16 Zeichen sein

### ISSUE THREAD

**Issue by mobfactor** [MakeMagazinDE/LED-Laufschrift#2]
Die Anleitung finde ich soweit verständlich, ich habe es zumindest im AP-Modus zum laufen bekommen. Der STA-Modus funktioniert bei mir nicht, da meine Fritzbox ein PW mit 20 Zeichen verwendet, das Programm aber nur 16 Stellen akzeptiert, wie kann man das ändern? Ich bin in C nicht so bewandert...
Es ist auf jeden Fall so, dass ein PW mit mehr als 16 Zeichen zu einem init fail beim ESP32 Sketch data upload führt, und zwar reproduzierbar.
In Zeile 173 des Hauptprogramms steht folgender Code: char AP_WLAN_PWD [21] = {0};                      /* String for Access Point password of WLAN */
Ich verstehe die Syntax nicht, aber könnte mir vorstellen, das da der Hase begraben liegt...

**Comment by Ptschulik** [comment]
HAbe eine neue Version an CT Make gesendet, die in Kürze veröffdentlicht werden sollte

**Comment by Ptschulik** [comment]
Bitte den Fehler schliessen!

**Comment by erik-wien** [comment]
Hi Ptschulik,

Noch einmal?

**Comment by mobfactor** [comment]
tut mir leid, dass ich erst jetzt aktiv geworden bin ich war einfach krank
